bug:
- all:
    - base-branch: ['master']
    - head-branch: ['^[\D\d]+\/(bug|fix)\/[\D\d]+|^(bug|fix)\/[\D\d]+']

enhancement:
- all:
    - base-branch: ['master']
    - head-branch: ['^[\D\d]+\/(enhancement|feature)\/[\D\d]+|^(enhancement|feature)\/[\D\d]+']

documentation:
- any:
    - changed-files: ['README.md']

engine:
- any:
    - changed-files: ['engines/**']

module:
- any:
    - changed-files: ['extensions/**']
