bug:
- all:
    - base-branch: ['master']
    - head-branch: ['^[\D\d]+\/bug\/[\D\d]+']

enhancement:
- all:
    - base-branch: ['master']
    - head-branch: ['^[\D\d]+\/enhancement\/[\D\d]+']

documentation:
- any:
    - changed-files: ['README.md']

engine:
- any:
    - changed-files: ['engines/**']

module:
- any:
    - changed-files: ['extensions/**']