name: Dashchan-Dvach build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  KEYSTORE_FILENAME: ${{ secrets.KEYSTORE_FILENAME }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Checkout keystore
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.KEYSTORE_DASHCHAN_REPO }}
        token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
        path: extensions/dvach/keystore

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build dvach with Gradle
      run: ./gradlew :extensions:dvach:assembleRelease
      
    - name: Build fourchan with Gradle
      run: ./gradlew :extensions:fourchan:assembleRelease
      
    - name: Build endchan with Gradle
      run: ./gradlew :extensions:endchan:assembleRelease

      
    - name: Upload APK - Dvach
      uses: actions/upload-artifact@v2
      with:
        name: DashchanDvach.apk
        path: extensions/dvach/build/outputs/apk/release/DashchanDvach-release.apk
        
    - name: Upload APK - Fourchan
      uses: actions/upload-artifact@v2
      with:
        name: DashchanFourchan.apk
        path: extensions/fourchan/build/outputs/apk/release/DashchanFourchan-release.apk
        
    - name: Upload APK - Endchan
      uses: actions/upload-artifact@v2
      with:
        name: DashchanEndchan.apk
        path: extensions/endchan/build/outputs/apk/release/DashchanEndchan-release.apk
      
