name: Dashchan-Dvach build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  KEYSTORE_FILENAME: ${{ secrets.KEYSTORE_FILENAME }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - module: dvach
            name: Dvach
          - module: fourchan
            name: Fourchan
          - module: endchan
            name: Endchan
          - module: cirno
            name: Cirno
          - module: sojakparty
            name: Sojakparty
          - module: refugedobrochan
            name: RefugeDobrochan
          - module: archivedmoe
            name: ArchivedMoe

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Checkout kyestore - for ${{ matrix.package.name }}
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.KEYSTORE_DASHCHAN_REPO }}
        token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
        path: extensions/${{ matrix.package.module }}/keystore

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build ${{ matrix.package.name }} with Gradle
      run: ./gradlew :extensions:${{ matrix.package.module }}:assembleRelease

    - name: Upload APK - ${{ matrix.package.name }}
      uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.package.name }}.apk
          path: extensions/${{ matrix.package.module }}/build/outputs/apk/release/Dashchan${{ matrix.package.name }}-release.apk
      
