name: "Auto labeling"
on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'master'

jobs:
  triage:
    name: "Checking for labels"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "TrixiEther/Dashchan-Extensions"
      - uses: actions/labeler@v5.0.0-alpha.1
        with:
          repo-token: "${{ secrets.ACCESS_TOKEN }}"
          sync-labels: true
          configuration-path: ".github/labeler.config.yml"
